<!DOCTYPE html>
<html lang="ko" xmlns:th="http://www.thymeleaf.org">
<head>
  <meta charset="UTF-8">
<title>Title</title>
</head>
<body>
<p>
  This is admin events page.
</p>
<ul>
  <li>placeName: <span th:text="${placeName} ?: _">?</span></li>
  <li>eventName: <span th:text="${eventName} ?: _">?</span></li>
  <li>eventStatus: <span th:text="${eventStatus} ?: _">?</span></li>
  <li>eventStartDatetime: <span th:text="${eventStartDatetime} ?: _">?</span></li>
  <li>eventEndDatetime: <span th:text="${eventEndDatetime} ?: _">?</span></li>
</ul>
</body>
</html>
